### PR TITLE
fix/defaultprops to default params

### PR DESCRIPTION
**Pull request by jaaneh**
### :pencil: Checklist

Make sure that your PR fulfills these requirements:

- [ ] Tests have been added for this feature.
- [ ] Code is properly documented in Storybook.
- [ ] All tests pass on your local machine.
- [x] Code has been linted with the proper rules.

### :page_facing_up: Description

When using any component from `react-twitch-embed`, the console spits out this warning:
> Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

image

This PR removes defaultProps and inlines defaults directly on the parameters instead, which should silence the above warning.

### CODE REVIEW

**Comment by moonstar-x** [comment]
Hey there, thank you for this.

I don't have any tooling set up for automatic versioning yet, would you please bump the version in both the `package.json` and `package-lock.json` files to `3.0.2`? 😄

**Comment by moonstar-x** [comment]
> Although if you want, I can generate a fresh lock file with lockfileVersion 3 which should handle it all. It'll bump minors for all related packages as well

Sure that could be great actually, thank you for your help!

**Comment by jaaneh** [comment]
> Sure that could be great actually, thank you for your help!

Of course! Done :)

I appreciate the work you've put into this package. Thank you!

**Comment by moonstar-x** [comment]
Awesome, thanks for your help!

**Pull request merged**
